### ISSUE TITLE
New Data!!!!

### ISSUE THREAD

**Issue by rcomeau14** [codefortulsa/food4thought#43]
I know we are working on new data uploading mechanism but we just finished the first (1/2 of total) data dump that OSDE provided. It is ready for upload and attached here!
[Copy 05.16.18 Food4ThoughtUpload EC.xlsx](https://github.com/codefortulsa/food4thought/files/2010398/Copy.05.16.18.Food4ThoughtUpload.EC.xlsx)

**Comment by aprilchomp** [comment]
Yay!
