### ISSUE TITLE
New About page content

### ISSUE THREAD

**Issue by aprilchomp** [codefortulsa/food4thought#48]
Add the following to about page: 
(Approved by Richard and HFO)

**What is the Oklahoma Summer Meals Program?**

The Oklahoma Summer Meals Program is administered by the Oklahoma State Department of Education. While school is out for the summer, over 100 sponsoring organizations, serving hundreds of sites across the state, provide no-cost meals to kids 18 and younger. Many sites serve both breakfast and lunch or lunch and a snack.

- Any child can receive a meal. 
- Meals must be eaten on site.
- No ID is necessary to participate.
- Children do not need to be accompanied by a parent to receive a meal.

**How do I find a meal site near me?**

- Clicking the “Find Food” button in the top right-hand corner of your screen will show a map of the nearest sites in a 10-mile radius. 

- Use the search bar located at the top of the page to look for a site near a different location. 

- Filter your search by sites that are “open now” and what types of meals served (i.e. breakfast, lunch, and dinner). 

- Select the “Get Directions” button for Google Map directions to the site. 

**About the website:**
This map was created in partnership with Code for Tulsa, Hunger Free Oklahoma, and the Oklahoma State Department of Education to help families locate summer meal sites faster than ever before. 
**About the partners:**
[Code for Tulsa logo]: Code for Tulsa is among about 70 Code for America “brigades” nationwide that help code and data specialist bring their technology skills to the process of connecting people to their local governments. The Tulsa brigade was one of the earliest to organize as the Code for America ideas expanded starting in 2009. 

[Hunger Free Oklahoma logo]: Hunger Free Oklahoma works to bring a unified, statewide voice to the issues and solutions surrounding hunger, with a goal to ensure all Oklahomans have access to affordable, nutritious food. We are leveraging the power of collaboration to solve hunger in Oklahoma by improving systems, policies, and practices.

[Oklahoma State Department of Education logo:]  The Oklahoma State Department of Education is charged with determining the policies and directing the administration and supervision of the public school system of Oklahoma. This includes administering the summer meals program, school breakfast and lunch programs, and afterschool meal programs.

**Comment by VicAgbasi** [comment]
I will update the page with this content later today. Thanks!

**Comment by rcomeau14** [comment]
Hi all, one more thing to add... sorry! No FAQS for now but we do have a concern about contact. Can we put contact info on every page to the effect of - Have questions or trouble using this map? Please contact Hunger Free Oklahoma at info@hungerfreeok.org or by calling 918 591 2460.

**Comment by lesleyjanenorton** [comment]
do we have a logo for codefortulsa?

**Comment by VicAgbasi** [comment]
i think carlos dropped one in the slack. I'll check

**Comment by VicAgbasi** [comment]
![cft full name 4x](https://user-images.githubusercontent.com/30783374/40881696-edd56620-6692-11e8-8d54-336761c77c3e.png)

**Comment by VicAgbasi** [comment]
here it is. @lesleyjanenorton
