### ISSUE TITLE
Address Search Sensitivity 

### ISSUE THREAD

**Issue by rcomeau14** [codefortulsa/food4thought#67]
From staff member testing:

> •	Typing in an address
> o	When I typed in my address, it would locate a totally different location with a similar address. I figured out that it will not properly locate the address if it is not completely written out, including the “OK”. 
> 	DOESN’T WORK Example: “2520 E. 2nd St. Tulsa, OK 74104 
> 	WORKS Example: “2520 East 2nd Street, Tulsa, Oklahoma 74104, United States
> o	Solution: If there is a way to locate abbreviations of streets, cardinal directions, state, and to omit the requirement of the United States at the end?
>

**Comment by VicAgbasi** [comment]
I typed in "2520 E. 2nd St. Tulsa, OK" and it took me to the correct place? It auto completed the address and gave the location a 74112 Zip Code. I'm not able to replicate the issue.
